@extends('layouts.main')
@section('content')
  <h3>Admin Dashboard</h3>

  <ul id="tabs" class="nav nav-tabs bold" data-tabs="tabs">
      <li class="active"><a href="#" data-toggle="tab">Sales Report</a></li>
      <li class="users"><a href="users">Back</a></li>
  </ul>
  
  <h4>Order Details</h4><hr>

  <?php 
        $page = Input::get('page', 1);
        $i = (10 * ($page -1)) + 1;
  ?> 
  {{ Form::open(array('url' => '/orders', 'method' => 'get', 'class' => 'filter')) }} <!-- Fliters --> 
    <div class="form-group col-md-12" style="padding: 0px;margin-bottom:10px;">
        <div class="col-md-12">
          <pre><b>Confirmed orders -</b> {{ $count['confirmed_orders'] }}&nbsp; <b>Pending orders -</b> {{ $count['pending_orders'] }}</pre>
           </pre>
        </div> 
       <div class="pull-left">
          @if(Auth::user()->usertype == 'admin') 
            <div class="col-md-3 dp">
              <label>Franchisee</label>
              {{ Form::select('franchise_id[]', $users['franchise_list'], Input::get('franchise_id'), array('class' => 'form-control input-md pull-right', 'style' => 'width: 65%;')) }}
            </div>
          @endif 
          <div class="form-group col-md-3 dp">
            <label>From Date<br><small>(Transaction Date)</small></label>
            <div class="input-append date pull-right" id="dp2" data-date="" data-date-format="dd-mm-yyyy">
              <input name="from_date" class="span2" size="16" type="text" value="<?php echo Input::get('from_date'); ?>" readonly />
              <label class="add-on"><i class="icon-calendar"></i></label>
            </div>
          </div>

          <div class="form-group col-md-3 dp">
            <label class=" pull-left">To Date<br><small>(Transaction Date)</small></label>
            <div class="input-append date" id="dp1" data-date="" data-date-format="dd-mm-yyyy">
              <input name="to_date" class="span2" size="16" type="text" value="<?php echo Input::get('to_date'); ?>" readonly />
              <label class="add-on"><i class="icon-calendar"></i></label>
            </div>
          </div>
          <div class="col-md-2" style="width:200px;margin-bottom:10px;"><label class=" pull-left">Status</label>
            {{ Form::select('status', $count['status'], Input::get('status'), array('class' => 'form-control input-md pull-right', 'style' => 'width: 60%;') ) }}
          </div>
          <div class="pull-right">
            <a href="/orders" class="btn btn-danger white" type="reset">Reset</a>
            {{ Form::submit('Filter', array('class' => 'btn btn-primary')) }}
            <button class="btn btn-primary" name="submit" value="download">Download</button>
          </div>
          
        </div>
      </div>  
     
    
  {{ Form::close() }}

  {{$users['pagination']}}
  
  <div id="my-tab-content" class="tab-content col-md-12">
    <div id="hdfc" class="tab-pane active">   
      
      <table class="table table-striped table-bordered col-md-12">
        <thead>
          <tr>
            <td>Sl.No.</td>
            <td>Full Name</td>
            <td>Email</td>
            <td>Phone</td>
            <td>Order Amount</td>
            <td>Order Discount</td>
            <td>Order Status</td>
            <td>Transaction Date</td>
            <td>Confirmed Date</td>
            @if(Auth::user()->usertype == 'admin')
              <td>Order Generated By</td>
            @endif
            <td>Print</td>
          </tr>
        </thead>
        <tbody>

          @foreach($users['users'] as $key => $user)
            <tr>
              <td>{{ $i++ }}</td>
              <td>{{ $user->first_name.' '.$user->last_name }}</td>
              <td>{{ $user->user_email }}</td>
              <td>{{ $user->phone_2 }}</td>
              <td>{{ number_format($user->order_total) }}</td>
              <td>{{ number_format($user->coupon_discount) }}</td>
              <td>@if($user->order_status == 'C')
                    {{ 'Confirmed' }} 
                  @elseif($user->order_status == 'P')
                    {{ 'Pending' }}
                  @elseif($user->order_status == 'H')
                    {{ 'Hold' }}
                  @elseif($user->order_status == 'X')
                    {{ 'Cancelled' }}
                  @elseif($user->order_status == 'R')
                    {{ 'Refunded' }}
                  @else
                    {{ '-' }} 
                  @endif
              </td>
              <td>{{ date('d-M-Y h.i.s A', $user->cdate) }}</td>
              <td>@if($user->order_status == 'C')
                    {{ date('d-M-Y h.i.s A', $user->mdate) }}
                    @else
                    {{ '-' }}
                  @endif
              </td>
              @if(Auth::user()->usertype == 'admin')
                <td>{{ $user->vm_hearaboutus }}</td>
              @endif
              <td>{{ "<a href=\"/orders/". $user->order_id ."\" target=\"_blank\"><span class=\"glyphicon glyphicon-print\"></span></a>" }}</td>
            </tr>
          @endforeach
        </tbody>
      </table>
    </div>

 </div>

@stop